spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
        name: test
#        url: jdbc:mysql://localhost:3306/library?characterEncoding=utf8
        url: jdbc:mysql://localhost:3306/library?characterEncoding=utf8
        username: root
#        password: Abcd1234
        password: wangmeng
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: managebooks@163.com
    password: 654321bm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.book.managebook.pojo
  configuration:
    map-underscore-to-camel-case: true

mail:
  fromMail:
    addr: managebooks@163.com
server:
  port: 8082
